[package]
name = "lb-node"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
lb-types = { workspace = true }
lb-forwarder = { workspace = true }
lb-controller = { workspace = true }
lb-config-manager = { workspace = true }
lb-hashing = { workspace = true }
lb-metrics = { workspace = true }
lb-io = { workspace = true }
lb-bgp = { workspace = true }
tokio = { workspace = true }
clap = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
arc-swap = { workspace = true }
dashmap = { workspace = true }
parking_lot = { workspace = true }
